# Generated by Django 6.0.5 on 2026-06-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
